from io import BytesIO

from docx import Document
from docx.shared import Pt

from fpdf import FPDF


# =========================================================
# TXT EXPORT
# =========================================================

def format_txt(text):
    """
    Convert text into TXT file bytes.
    """
    return text.encode("utf-8")


# =========================================================
# DOCX EXPORT
# =========================================================

def format_docx(text, doc_type="Legal Document"):
    """
    Create a DOCX document from generated legal text.
    """

    document = Document()

    # -------------------------
    # Title
    # -------------------------

    title = document.add_paragraph()

    title_run = title.add_run(
        doc_type.upper()
    )

    title_run.bold = True
    title_run.font.name = "Times New Roman"
    title_run.font.size = Pt(16)

    # -------------------------
    # Document Content
    # -------------------------

    for line in text.splitlines():

        line = line.strip()

        # Empty line
        if not line:
            document.add_paragraph()
            continue

        paragraph = document.add_paragraph()

        run = paragraph.add_run(line)

        run.font.name = "Times New Roman"
        run.font.size = Pt(12)

        # Make simple headings bold
        if (
            line.isupper()
            or line.startswith("1.")
            or line.startswith("2.")
            or line.startswith("3.")
            or line.startswith("4.")
            or line.startswith("5.")
            or line.startswith("6.")
            or line.startswith("7.")
            or line.startswith("8.")
            or line.startswith("9.")
        ):
            run.bold = True

    # -------------------------
    # Footer
    # -------------------------

    footer = document.sections[0].footer

    footer_paragraph = footer.paragraphs[0]

    footer_run = footer_paragraph.add_run(
        "Generated by LegalEase"
    )

    footer_run.font.name = "Times New Roman"
    footer_run.font.size = Pt(9)

    # -------------------------
    # Save in memory
    # -------------------------

    output = BytesIO()

    document.save(output)

    output.seek(0)

    return output.getvalue()


# =========================================================
# PDF EXPORT
# =========================================================

def format_pdf(text, doc_type="Legal Document"):
    """
    Create a PDF document from generated legal text.
    """

    pdf = FPDF()

    # Page settings
    pdf.set_auto_page_break(
        auto=True,
        margin=20
    )

    pdf.add_page()

    # -------------------------
    # Title
    # -------------------------

    pdf.set_font(
        "Helvetica",
        "B",
        16
    )

    pdf.cell(
        0,
        10,
        doc_type.upper(),
        align="C"
    )

    pdf.ln(15)

    # -------------------------
    # Clean text
    # -------------------------

    safe_text = (
        text
        .replace("–", "-")
        .replace("—", "-")
        .replace("“", '"')
        .replace("”", '"')
        .replace("‘", "'")
        .replace("’", "'")
        .replace("•", "-")
    )

    # -------------------------
    # Document content
    # -------------------------

    for line in safe_text.splitlines():

        line = line.strip()

        # Empty line
        if not line:
            pdf.ln(5)
            continue

        # Simple heading detection
        if (
            line.isupper()
            or line.startswith("1.")
            or line.startswith("2.")
            or line.startswith("3.")
            or line.startswith("4.")
            or line.startswith("5.")
            or line.startswith("6.")
            or line.startswith("7.")
            or line.startswith("8.")
            or line.startswith("9.")
        ):

            pdf.set_font(
                "Helvetica",
                "B",
                11
            )

        else:

            pdf.set_font(
                "Helvetica",
                "",
                11
            )

        # Convert unsupported characters
        line = (
            line
            .encode(
                "latin-1",
                errors="replace"
            )
            .decode("latin-1")
        )

        # Add paragraph
        pdf.multi_cell(
            0,
            7,
            line
        )

    # -------------------------
    # Footer
    # -------------------------

    pdf.set_y(-15)

    pdf.set_font(
        "Helvetica",
        "",
        8
    )

    pdf.cell(
        0,
        10,
        "Generated by LegalEase",
        align="C"
    )

    # -------------------------
    # Return PDF as bytes
    # -------------------------

    output = pdf.output(
        dest="S"
    )

    # Compatible with different FPDF versions
    if isinstance(output, str):
        return output.encode("latin-1")

    return bytes(output)


# =========================================================
# HTML PREVIEW
# =========================================================

def format_html_preview(text):
    """
    Create simple HTML preview for the document.
    """

    escaped_text = (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    escaped_text = escaped_text.replace(
        "\n",
        "<br>"
    )

    return f"""
    <div style="
        font-family: Times New Roman;
        line-height: 1.6;
        padding: 20px;
    ">
        {escaped_text}
    </div>
    """